# Conclusions {#conclusions}

In this thesis the emphasis was on long memory stochastic processes. Traditional ARIMA models were generalized to allow for zero frequency fractional integration instead of zero frequency integer integration only. The fractional parameter describes the long memory behavior of a stochastic process, thereby modeling low frequency behavior more flexible than when trying to model this behavior by e.g. an autoregressive filter. The autoregressive and moving-average components can be applied to describe short-term behavior.

From the simulation experiments we concluded that the estimator of the population mean of fractionally integrated series can be seriously biased. In Geweke and Porter---Hudak (1983) the population mean has been used in the simulation study on the autocorrelation function of such series. Our experiments show that computation of this function given empirical mean leads to underestimation at all autocorrelation lags. One can partially circumvent this problem by modeling first differences.

Whereas (augmented) Dickey-Fuller tests are not developed for fractionally integrated processes, zero frequency unit root tests based on estimation of the parameter of fractional integration can be used in case of fracional as well as integer integrated processes. In the second example Dickey---Fuller rejects the integer unit root against lower order fractional unit root.

Estimation of the fractional parameter of integration is performed by the two-stage semi-parametric Geweke and Porter-Hudak (1983) procedure. Although estimation of this parameter by frequency domain log periodogram regression is independent from the mean of the series, the influence of short-run ARMA parameters can lead to serious bias in the estimator. This bias showed up when analyzing quarterly real US GNP (s.a.). Simultaneous estimation of the long and short memory parameters according to Sowell (1992a,b) performs better in this case.

From the frequency domain periodograms it appeared that imposing a zero-frequency unit root by taking first differences of realizations of some process can lead to overdifferentiation. With respect to long run forecasting taking first differences is preferred over the fractional alternatives in case of quarterly real US GNP (s.a.). Overdifferentiation is present when first differences of Trier oak tree ring widths are taken. However, there is some zero frequency unit root long memory of fractional order. As the fractional alternatives are preferred, mean reversion under the fractional alternatives is present and the series is estimated as stationary although non-stationarity cannot be excluded.

The oak tree data give a very clear illustration of the applicability of time series modeling in empirical work.
